name: for_jop
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  animated_bottom_navigation_bar: ^0.1.2+2
  circular_reveal_animation: ^1.1.5
  flutter_staggered_animations:
  provider:



flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: cairo
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
    - family: caira
      fonts:
        - asset: assets/fonts/cairo_regular.ttf
